=== Starfie1d1272/cs2-demo-format/spec/blinds.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "roundNumber": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "tick": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "flashId": {
        "type": [
          "string",
          "null"
        ]
      },
      "flasherIndex": {
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      },
      "flashedIndex": {
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      },
      "durationSeconds": {
        "type": "number",
        "minimum": 0,
        "maximum": 6
      }
    },
    "required": [
      "roundNumber",
      "tick",
      "flashId",
      "flasherIndex",
      "flashedIndex",
      "durationSeconds"
    ],
    "additionalProperties": false
  }
}

=== Starfie1d1272/cs2-demo-format/fixtures/v3-mid/blinds.json
[{"roundNumber":1,"tick":6052,"flashId":"160-5948","flasherIndex":4,"flashedIndex":3,"durationSeconds":1.902},{"roundNumber":1,"tick":6052,"flashId":"160-5948","flasherIndex":4,"flashedIndex":7,"durationSeconds":3.076},{"roundNumber":2,"tick":12763,"flashId":"94-12659","flasherIndex":3,"flashedIndex":0,"durationSeconds":4.43},{"roundNumber":2,"tick":12763,"flashId":"94-12659","flasherIndex":3,"flashedIndex":2,"durationSeconds":3.871},{"roundNumber":2,"tick":12763,"flashId":"94-12659","flasherIndex":3,"flashedIndex":6,"durationSeconds":0.68},{"roundNumber":2,"tick":12763,"flashId":"94-12659","flasherIndex":3,"flashedIndex":7,"durationSeconds":4.312},{"roundNumber":3,"tick":17624,"flashId":"273-17520","flasherIndex":4,"flashedIndex":4,"durationSeconds":0.563},{"roundNumber":3,"tick":20718,"flashId":"320-20614","flasherIndex":1,"flashedIndex":8,"durationSeconds":0.874},{"roundNumber":3,"tick":20718,"flashId":"320-20614","flasherIndex":1,"flashedIndex":6,"durationSeconds":4.977},{"roundNumber":3,"tick":20718,"flashId":"320-20614","flasherIndex":1,"flashedIndex":3,"durationSeconds":0.807},{"roundNumber":4,"tick":26683,"flashId":"374-26579","flasherIndex":1,"flashedIndex":2,"durationSeconds":1.105},{"roundNumber":4,"tick":26683,"flashId":"374-26579","flasherIndex":1,"flashedIndex":1,"durationSeconds":1.998},{"roundNumber":5,"tick":37073,"flashId":"267-36969","flasherIndex":6,"flashedIndex":0,"durationSeconds":4.808},{"roundNumber":5,"tick":37073,"flashId":"267-36969","flasherIndex":6,"flashedIndex":2,"durationSeconds":4.812},{"roundNumber":5,"tick":37459,"flashId":"114-37355","flasherIndex":4,"flashedIndex":6,"durationSeconds":4.151},{"roundNumber":5,"tick":37567,"flashId":"153-37463","flasherIndex":1,"flashedIndex":4,"durationSeconds":0.984},{"roundNumber":5,"tick":37567,"flashId":"153-37463","flasherIndex":1,"flashedIndex":2,"durationSeconds":4.571},{"roundNumber":5,"tick":37567,"flashId":"153-37463","flasherIndex":1,"flashedIndex":1,"durationSeconds":0.993},{"roundNumber":6,"tick":42714,"flashId":"66-42610","flasherIndex":8,"flashedIndex":8,"durationSeconds":0.755},{"roundNumber":6,"tick":42714,"flashId":"66-42610","flasherIndex":8,"flashedIndex":1,"durationSeconds":1.009},{"roundNumber":6,"tick":42978,"flashId":"423-42874","flasherIndex":5,"flashedIndex":5,"durationSeconds":2.105},{"roundNumber":6,"tick":42999,"flashId":"260-42895","flasherIndex":4,"flashedIndex":4,"durationSeconds":4.445},{"roundNumber":6,"tick":43024,"flashId":"98-42920","flasherIndex":9,"flashedIndex":9,"durationSeconds":3.487},{"roundNumber":6,"tick":44903,"flashId":"409-44799","flasherIndex":3,"flashedIndex":2,"durationSeconds":2.817},{"roundNumber":8,"tick":58317,"flashId":"299-58213","flasherIndex":5,"flashedIndex":9,"durationSeconds":2.311},{"roundNumber":8,"tick":58317,"flashId":"299-58213","flasherIndex":5,"flashedIndex":5,"durationSeconds":0.943},{"roundNumber":8,"tick":58444,"flashId":"97-58340","flasherIndex":4,"flashedIndex":4,"durationSeconds":1.684},{"roundNumber":8,"tick":58444,"flashId":"97-58340","flasherIndex":4,"flashedIndex":0,"durationSeconds":0.13},{"roundNumber":8,"tick":58964,"flashId":"281-58860","flasherIndex":0,"flashedIndex":5,"durationSeconds":3.54},{"roundNumber":8,"tick":63899,"flashId":"142-63795","flasherIndex":4,"flashedIndex":9,"durationSeconds":4.845},{"roundNumber":8,"tick":63899,"flashId":"142-63795","flasherIndex":4,"flashedIndex":5,"durationSeconds":0.92},{"roundNumber":8,"tick":63900,"flashId":"317-63796","flasherIndex":5,"flashedIndex":9,"durationSeconds":4.829},{"roundNumber":8,"tick":63900,"flashId":"317-63796","flasherIndex":5,"flashedIndex":5,"durationSeconds":0.905},{"roundNumber":9,"tick":68672,"flashId":"388-68568","flasherIndex":5,"flashedIndex":5,"durationSeconds":0.76},{"roundNumber":9,"tick":70105,"flashId":"261-70001","flasherIndex":3,"flashedIndex":5,"durationSeconds":4.094},{"roundNumber":9,"tick":70319,"flashId":"95-70215","flasherIndex":1,"flashedIndex":3,"durationSeconds":3.736},{"roundNumber":9,"tick":70319,"flashId":"95-70215","flasherIndex":1,"flashedIndex":7,"durationSeconds":3.431},{"roundNumber":9,"tick":70319,"flashId":"95-70215","flasherIndex":1,"flashedIndex":5,"durationSeconds":2.707},{"roundNumber":10,"tick":77460,"flashId":"373-77356","flasherIndex":4,"flashedIndex":4,"durationSeconds":2.028},{"roundNumber":10,"tick":77460,"flashId":"373-77356","flasherIndex":4,"flashedIndex":0,"durationSeconds":3.517},{"roundNumber":10,"tick":77460,"flashId":"373-77356","flasherIndex":4,"flashedIndex":2,"durationSeconds":0.983},{"roundNumber":10,"tick":77460,"flashId":"373-77356","flasherIndex":4,"flashedIndex":3,"durationSeconds":0.652},{"roundNumber":10,"tick":77460,"flashId":"373-77356","flasherIndex":4,"flashedIndex":1,"durationSeconds":0.961},{"roundNumber":10,"tick":77550,"flashId":"411-77446","flasherIndex":0,"flashedIndex":4,"durationSeconds":0.877},{"roundNumber":10,"tick":77550,"flashId":"411-77446","flasherIndex":0,"flashedIndex":8,"durationSeconds":0.393},{"roundNumber":10,"tick":77550,"flashId":"411-77446","flasherIndex":0,"flashedIndex":0,"durationSeconds":2.11},{"roundNumber":10,"tick":77550,"flashId":"411-77446","flasherIndex":0,"flashedIndex":2,"durationSeconds":0.834},{"roundNumber":10,"tick":77550,"flashId":"411-77446","flasherIndex":0,"flashedIndex":3,"durationSeconds":1.58},{"roundNumber":10,"tick":77550,"flashId":"411-77446","flasherIndex":0,"flashedIndex":1,"durationSeconds":0.818},{"roundNumber":10,"tick":77839,"flashId":"124-77735","flasherIndex":3,"flashedIndex":3,"durationSeconds":0.888},{"roundNumber":11,"tick":81086,"flashId":"389-80982","flasherIndex":9,"flashedIndex":8,"durationSeconds":1.028},{"roundNumber":11,"tick":81086,"flashId":"389-80982","flasherIndex":9,"flashedIndex":9,"durationSeconds":0.658},{"roundNumber":11,"tick":81086,"flashId":"389-80982","flasherIndex":9,"flashedIndex":7,"durationSeconds":2.078},{"roundNumber":11,"tick":81212,"flashId":"162-81108","flasherIndex":9,"flashedIndex":8,"durationSeconds":0.127},{"roundNumber":11,"tick":81212,"flashId":"162-81108","flasherIndex":9,"flashedIndex":9,"durationSeconds":0.989},{"roundNumber":11,"tick":81212,"flashId":"162-81108","flasherIndex":9,"flashedIndex":7,"durationSeconds":0.248},{"roundNumber":11,"tick":84330,"flashId":"128-84226","flasherIndex":8,"flashedIndex":1,"durationSeconds":1.02},{"roundNumber":11,"tick":84896,"flashId":"331-84792","flasherIndex":5,"flashedIndex":0,"durationSeconds":3.626},{"roundNumber":11,"tick":84896,"flashId":"331-84792","flasherIndex":5,"flashedIndex":9,"durationSeconds":3.208},{"roundNumber":11,"tick":84896,"flashId":"331-84792","flasherIndex":5,"flashedIndex":5,"durationSeconds":0.818},{"roundNumber":11,"tick":86531,"flashId":"359-86427","flasherIndex":6,"flashedIndex":2,"durationSeconds":0.237},{"roundNumber":11,"tick":86531,"flashId":"359-86427","flasherIndex":6,"flashedIndex":6,"durationSeconds":0.748},{"roundNumber":12,"tick":89547,"flashId":"423-89443","flasherIndex":0,"flashedIndex":8,"durationSeconds":1.811},{"roundNumber":12,"tick":89547,"flashId":"423-89443","flasherIndex":0,"flashedIndex":0,"durationSeconds":0.624},{"roundNumber":12,"tick":89547,"flashId":"423-89443","flasherIndex":0,"flashedIndex":3,"durationSeconds":1.096},{"roundNumber":12,"tick":89547,"flashId":"423-89443","flasherIndex":0,"flashedIndex":5,"durationSeconds":2.367},{"roundNumber":12,"tick":91309,"flashId":"146-91205","flasherIndex":8,"flashedIndex":4,"durationSeconds":3.518},{"roundNumber":12,"tick":91309,"flashId":"146-91205","flasherIndex":8,"flashedIndex":0,"durationSeconds":1.984},{"roundNumber":12,"tick":93110,"flashId":"121-93006","flasherIndex":1,"flashedIndex":9,"durationSeconds":0.581},{"roundNumber":12,"tick":93449,"flashId":"96-93345","flasherIndex":3,"flashedIndex":2,"durationSeconds":0.146},{"roundNumber":12,"tick":93449,"flashId":"96-93345","flasherIndex":3,"flashedIndex":3,"durationSeconds":0.963},{"roundNumber":12,"tick":93449,"flashId":"96-93345","flasherIndex":3,"flashedIndex":1,"durationSeconds":0.779},{"roundNumber":13,"tick":101923,"flashId":"188-101819","flasherIndex":9,"flashedIndex":3,"durationSeconds":0.596},{"roundNumber":13,"tick":102118,"flashId":"298-102014","flasherIndex":9,"flashedIndex":8,"durationSeconds":0.783},{"roundNumber":13,"tick":102118,"flashId":"298-102014","flasherIndex":9,"flashedIndex":3,"durationSeconds":3.279},{"roundNumber":14,"tick":109688,"flashId":"191-109584","flasherIndex":9,"flashedIndex":4,"durationSeconds":0.898},{"roundNumber":14,"tick":109688,"flashId":"191-109584","flasherIndex":9,"flashedIndex":2,"durationSeconds":4.016},{"roundNumber":14,"tick":109688,"flashId":"191-109584","flasherIndex":9,"flashedIndex":6,"durationSeconds":1.765},{"roundNumber":15,"tick":113963,"flashId":"188-113859","flasherIndex":9,"flashedIndex":8,"durationSeconds":3.646},{"roundNumber":15,"tick":113963,"flashId":"188-113859","flasherIndex":9,"flashedIndex":7,"durationSeconds":0.778},{"roundNumber":15,"tick":114386,"flashId":"330-114282","flasherIndex":5,"flashedIndex":6,"durationSeconds":1.23},{"roundNumber":15,"tick":114386,"flashId":"330-114282","flasherIndex":5,"flashedIndex":3,"durationSeconds":1.397},{"roundNumber":15,"tick":114386,"flashId":"330-114282","flasherIndex":5,"flashedIndex":5,"durationSeconds":1.488},{"roundNumber":15,"tick":115917,"flashId":"323-115813","flasherIndex":1,"flashedIndex":0,"durationSeconds":1.829},{"roundNumber":15,"tick":115917,"flashId":"323-115813","flasherIndex":1,"flashedIndex":6,"durationSeconds":4.77},{"roundNumber":15,"tick":115917,"flashId":"323-115813","flasherIndex":1,"flashedIndex":9,"durationSeconds":4.162},{"roundNumber":15,"tick":115917,"flashId":"323-115813","flasherIndex":1,"flashedIndex":5,"durationSeconds":4.287},{"roundNumber":16,"tick":118971,"flashId":"141-118867","flasherIndex":6,"flashedIndex":2,"durationSeconds":4.329},{"roundNumber":16,"tick":119130,"flashId":"386-119026","flasherIndex":0,"flashedIndex":2,"durationSeconds":4.555},{"roundNumber":16,"tick":120135,"flashId":"473-120031","flasherIn
