=== Starfie1d1272/cs2-demo-format/spec/bombs.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "roundNumber": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "tick": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "type": {
        "type": "string",
        "enum": [
          "plant_begin",
          "planted",
          "defuse_begin",
          "defused",
          "exploded",
          "dropped",
          "picked_up"
        ]
      },
      "site": {
        "anyOf": [
          {
            "type": "string",
            "enum": [
              "a",
              "b"
            ]
          },
          {
            "type": "null"
          }
        ]
      },
      "actorIndex": {
        "anyOf": [
          {
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          {
            "type": "null"
          }
        ]
      },
      "position": {
        "type": "object",
        "properties": {
          "x": {
            "type": "integer",
            "minimum": -9007199254740991,
            "maximum": 9007199254740991
          },
          "y": {
            "type": "integer",
            "minimum": -9007199254740991,
            "maximum": 9007199254740991
          },
          "z": {
            "type": "integer",
            "minimum": -9007199254740991,
            "maximum": 9007199254740991
          }
        },
        "required": [
          "x",
          "y",
          "z"
        ],
        "additionalProperties": false
      }
    },
    "required": [
      "roundNumber",
      "tick",
      "type",
      "site",
      "actorIndex",
      "position"
    ],
    "additionalProperties": false
  }
}

=== Starfie1d1272/cs2-demo-format/fixtures/v3-mid/bombs.json
[{"roundNumber":1,"tick":3092,"type":"dropped","site":null,"actorIndex":4,"position":{"x":-1017,"y":-752,"z":64}},{"roundNumber":1,"tick":4887,"type":"picked_up","site":null,"actorIndex":3,"position":{"x":-1108,"y":-600,"z":64}},{"roundNumber":1,"tick":6183,"type":"plant_begin","site":"b","actorIndex":3,"position":{"x":-1136,"y":688,"z":-2}},{"roundNumber":1,"tick":6383,"type":"planted","site":"b","actorIndex":3,"position":{"x":-1136,"y":689,"z":-2}},{"roundNumber":2,"tick":10084,"type":"picked_up","site":null,"actorIndex":3,"position":{"x":-399,"y":-1514,"z":-12}},{"roundNumber":2,"tick":13193,"type":"plant_begin","site":"a","actorIndex":3,"position":{"x":1249,"y":1796,"z":-192}},{"roundNumber":3,"tick":15012,"type":"picked_up","site":null,"actorIndex":0,"position":{"x":-468,"y":-1517,"z":2}},{"roundNumber":3,"tick":15321,"type":"dropped","site":null,"actorIndex":0,"position":{"x":-993,"y":-834,"z":64}},{"roundNumber":3,"tick":15441,"type":"picked_up","site":null,"actorIndex":0,"position":{"x":-807,"y":-608,"z":77}},{"roundNumber":3,"tick":16813,"type":"dropped","site":null,"actorIndex":0,"position":{"x":-643,"y":-465,"z":64}},{"roundNumber":3,"tick":16990,"type":"picked_up","site":null,"actorIndex":3,"position":{"x":-363,"y":-218,"z":0}},{"roundNumber":3,"tick":20056,"type":"plant_begin","site":"a","actorIndex":3,"position":{"x":1058,"y":1728,"z":-180}},{"roundNumber":3,"tick":20256,"type":"planted","site":"a","actorIndex":3,"position":{"x":1059,"y":1732,"z":-184}},{"roundNumber":4,"tick":26871,"type":"dropped","site":null,"actorIndex":2,"position":{"x":1213,"y":618,"z":-152}},{"roundNumber":5,"tick":31944,"type":"dropped","site":null,"actorIndex":4,"position":{"x":-620,"y":-1379,"z":2}},{"roundNumber":5,"tick":32368,"type":"picked_up","site":null,"actorIndex":3,"position":{"x":-807,"y":-1212,"z":32}},{"roundNumber":5,"tick":32434,"type":"dropped","site":null,"actorIndex":3,"position":{"x":-960,"y":-1164,"z":64}},{"roundNumber":5,"tick":36132,"type":"picked_up","site":null,"actorIndex":4,"position":{"x":-1111,"y":-961,"z":64}},{"roundNumber":5,"tick":38183,"type":"plant_begin","site":"b","actorIndex":4,"position":{"x":-1136,"y":700,"z":-2}},{"roundNumber":5,"tick":38383,"type":"planted","site":"b","actorIndex":4,"position":{"x":-1136,"y":700,"z":-2}},{"roundNumber":5,"tick":38876,"type":"defuse_begin","site":"b","actorIndex":9,"position":{"x":-1155,"y":641,"z":-4}},{"roundNumber":5,"tick":39516,"type":"defused","site":"b","actorIndex":9,"position":{"x":-1155,"y":641,"z":-4}},{"roundNumber":6,"tick":41326,"type":"dropped","site":null,"actorIndex":1,"position":{"x":482,"y":-1227,"z":2}},{"roundNumber":6,"tick":43373,"type":"picked_up","site":null,"actorIndex":2,"position":{"x":644,"y":-1044,"z":-12}},{"roundNumber":6,"tick":45521,"type":"dropped","site":"b","actorIndex":2,"position":{"x":-1576,"y":365,"z":0}},{"roundNumber":7,"tick":52757,"type":"dropped","site":null,"actorIndex":1,"position":{"x":1547,"y":925,"z":-151}},{"roundNumber":7,"tick":52871,"type":"picked_up","site":null,"actorIndex":2,"position":{"x":1693,"y":1042,"z":-152}},{"roundNumber":7,"tick":53134,"type":"dropped","site":null,"actorIndex":2,"position":{"x":1751,"y":1464,"z":-152}},{"roundNumber":7,"tick":53140,"type":"picked_up","site":null,"actorIndex":3,"position":{"x":1750,"y":1427,"z":-152}},{"roundNumber":7,"tick":53204,"type":"dropped","site":null,"actorIndex":3,"position":{"x":1780,"y":1500,"z":-148}},{"roundNumber":8,"tick":62050,"type":"plant_begin","site":"a","actorIndex":3,"position":{"x":1023,"y":1860,"z":-192}},{"roundNumber":8,"tick":62250,"type":"planted","site":"a","actorIndex":3,"position":{"x":1022,"y":1863,"z":-192}},{"roundNumber":8,"tick":63927,"type":"defuse_begin","site":"a","actorIndex":5,"position":{"x":1058,"y":1824,"z":-192}},{"roundNumber":8,"tick":64247,"type":"defused","site":"a","actorIndex":5,"position":{"x":1058,"y":1824,"z":-192}},{"roundNumber":9,"tick":66176,"type":"dropped","site":null,"actorIndex":2,"position":{"x":503,"y":-804,"z":0}},{"roundNumber":9,"tick":67831,"type":"picked_up","site":null,"actorIndex":2,"position":{"x":444,"y":-541,"z":-12}},{"roundNumber":9,"tick":70653,"type":"plant_begin","site":"b","actorIndex":2,"position":{"x":-1136,"y":654,"z":-2}},{"roundNumber":9,"tick":70853,"type":"planted","site":"b","actorIndex":2,"position":{"x":-1136,"y":654,"z":-2}},{"roundNumber":9,"tick":72019,"type":"defuse_begin","site":"b","actorIndex":8,"position":{"x":-1154,"y":655,"z":-4}},{"roundNumber":9,"tick":72128,"type":"defuse_begin","site":"b","actorIndex":8,"position":{"x":-1143,"y":668,"z":-2}},{"roundNumber":9,"tick":72363,"type":"defuse_begin","site":"b","actorIndex":8,"position":{"x":-1136,"y":666,"z":-2}},{"roundNumber":9,"tick":72514,"type":"defuse_begin","site":"b","actorIndex":7,"position":{"x":-1152,"y":607,"z":-4}},{"roundNumber":9,"tick":72834,"type":"defused","site":"b","actorIndex":7,"position":{"x":-1152,"y":607,"z":-4}},{"roundNumber":10,"tick":77785,"type":"dropped","site":"b","actorIndex":4,"position":{"x":-1343,"y":426,"z":0}},{"roundNumber":11,"tick":81201,"type":"dropped","site":null,"actorIndex":3,"position":{"x":-725,"y":-702,"z":106}},{"roundNumber":11,"tick":83380,"type":"picked_up","site":null,"actorIndex":0,"position":{"x":-613,"y":-546,"z":64}},{"roundNumber":11,"tick":85562,"type":"plant_begin","site":"b","actorIndex":0,"position":{"x":-1136,"y":700,"z":-2}},{"roundNumber":11,"tick":85762,"type":"planted","site":"b","actorIndex":0,"position":{"x":-1136,"y":700,"z":-2}},{"roundNumber":12,"tick":88639,"type":"dropped","site":null,"actorIndex":1,"position":{"x":-823,"y":-1290,"z":32}},{"roundNumber":12,"tick":89141,"type":"picked_up","site":null,"actorIndex":3,"position":{"x":-851,"y":-1213,"z":35}},{"roundNumber":12,"tick":93661,"type":"dropped","site":null,"actorIndex":3,"position":{"x":-789,"y":383,"z":-56}},{"roundNumber":12,"tick":93807,"type":"picked_up","site":null,"actorIndex":2,"position":{"x":-857,"y":325,"z":-56}},{"roundNumber":12,"tick":93991,"type":"plant_begin","site":"b","actorIndex":2,"position":{"x":-1083,"y":600,"z":-2}},{"roundNumber":12,"tick":94191,"type":"planted","site":"b","actorIndex":2,"position":{"x":-1083,"y":600,"z":-2}},{"roundNumber":13,"tick":99892,"type":"dropped","site":null,"actorIndex":9,"position":{"x":-960,"y":-961,"z":65}},{"roundNumber":13,"tick":99913,"type":"picked_up","site":null,"actorIndex":6,"position":{"x":-812,"y":-841,"z":106}},{"roundNumber":13,"tick":102038,"type":"dropped","site":null,"actorIndex":6,"position":{"x":-1673,"y":120,"z":1}},{"roundNumber":13,"tick":102152,"type":"picked_up","site":null,"actorIndex":9,"position":{"x":-1577,"y":134,"z":1}},{"roundNumber":13,"tick":104294,"type":"dropped","site":null,"actorIndex":9,"position":{"x":-525,"y":2009,"z":16}},{"roundNumber":14,"tick":109775,"type":"dropped","site":"b","actorIndex":6,"position":{"x":-1375,"y":575,"z":0}},{"roundNumber":14,"tick":109781,"type":"picked_up","site":"b","actorIndex":7,"position":{"x":-1409,"y":552,"z":0}},{"roundNumber":14,"tick":109790,"type":"dropped","site":"b","actorIndex":7,"position":{"x":-1405,"y":563,"z":0}},{"roundNumber":15,"tick":111900,"type":"dropped","site":null,"actorIndex":6,"position":{"x":-1018,"y":-1074,"z":66}},{"roundNumber":15,"tick":112062,"type":"picked_up","site":null,"actorIndex":9,"position":{"x":-1070,"y":-875,"z":64}},{"roundNumber":15,"tick":112267,"type":"dropped","site":null,"actorIndex":9,"position":{"x":-527,"y":-381,"z":56}},{"roundNumber":15,"tick":113295,"type":"picked_up","site":null,"actorIndex":6,"position":{"x":-454,"y":-273,"z":0}},{"roundNumber":15,"tick":116220,"type":"dropped","site":"a","actorIndex":6,"position":{"x":936,"y":1919,"z":-152}},{"roundNumber":16,"tick":118616,"type":"dropped","site":null,"actorIndex":5,"position":{"x":-871,"y":-744,"z":64}},{"roundNumber":16,"tick":119711,"type":"picked_up","site":null,"actorIndex":5,"position":{"x":-644,"y":-531,"z":64}},{"roundNumber":16,"tick":121775,"type":"dropped","site":null,"actorIndex":5,"position":{"x":976,"y":1254,"z":-88}},{"roundNumber":16,"tick":121914,"type":"picked_up","site":null,"actorIndex":8,"position":{"x":961,"y":1413,"z":-88}},{"roundNumber":16,"tick":121985,"type":"dropped","site":null,"actorIndex":8,"position":{"x":852,"y":1565,"z":-88}},{"roundNumber":16,"tick":122575,"type":"picked_up","site":"a","actorIndex":8,"position":{"x":1082,"y":1854,"z":-192}},{"roundNumber":16,"tick":122745,"type":"plant_begin","site":"a","actorIndex":8,"position":{"x":1214,"y":1992,"z":-192}},{"roundNumber":16,"tick":123258,"type":"dropped","site":"a","actorIndex":8,"position":{"x":1097,"y":1434,"z":-106}},{"roundNumber":17,"tick":125131,"type":"picked_up","site":null,"actorIndex":9,"position":{"x":-329,"y":-1556,"z":-12}},{"roundNumber":17,"tick":126572,"type":"dropped","site":"b","actorIndex":9,"position":{"x":-1061,"y":346,"z":-23}},{"roundNumber":18,"tick":131040,"type":"dropped","site":null,"actorIndex":9,"position":{"x":-1155,"y":1563,"z":-31}},{"roundNumber":18,"tick":131047,"type":"picked_up","site":null,"actorIndex":5,"position":{"x":-1105,"y":1511,"z":-31}},{"roundNumber":18,"tick":131066,"type":"dropped","site":null,"actorIndex":5,"position":{"x":-1104,"y":1510,"z":-31}},{"roundNumber":19,"tick":133357,"type":"picked_up","site":null,"actorIndex":5,"position":{"x":-271,"y":-1528,"z":-12}},{"roundNumber":19,"tick":133697,"type":"dropped","site":null,"actorIndex":5,"position":{"x":-834,"y":-734,"z":64}},{"roundNumber":19,"tick":133818,"type":"picked_up","site":null,"actorIndex":6,"position":{"x":-567,"y":-491,"z":64}},{"roundNumber":19,"tick":134573,"type":"dropped","site":null,"actorIndex":6,"position":{"x":874,"y":-267,"z":-32}},{"roundNumber":19,"tick":134595,"type":"picked_up","site":null,"actorIndex":7,"position":{"x":821,"y":-102,"z":-96}},{"roundNumber":19,"tick":138005,"type":"plant_begin","site":"a","actorIndex":7,"position":{"x":1279,"y":1974,"z":-192}},{"roundNumber":19,"tick":138205,"type":"planted","site":"a","actorIndex":7,"
