=== Starfie1d1272/cs2-demo-format/spec/damages.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "roundNumber": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "tick": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "attackerIndex": {
        "anyOf": [
          {
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          {
            "type": "null"
          }
        ]
      },
      "victimIndex": {
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      },
      "weapon": {
        "type": "string",
        "minLength": 1
      },
      "hitgroup": {
        "type": "string",
        "enum": [
          "generic",
          "head",
          "chest",
          "stomach",
          "left_arm",
          "right_arm",
          "left_leg",
          "right_leg",
          "gear",
          "neck"
        ]
      },
      "healthDamage": {
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      },
      "healthDamageRaw": {
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      },
      "armorDamage": {
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      },
      "victimHealthBefore": {
        "type": "integer",
        "minimum": 0,
        "maximum": 100
      },
      "victimArmorAfter": {
        "type": "integer",
        "minimum": 0,
        "maximum": 100
      },
      "attackerPosition": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "x": {
                "type": "integer",
                "minimum": -9007199254740991,
                "maximum": 9007199254740991
              },
              "y": {
                "type": "integer",
                "minimum": -9007199254740991,
                "maximum": 9007199254740991
              },
              "z": {
                "type": "integer",
                "minimum": -9007199254740991,
                "maximum": 9007199254740991
              }
            },
            "required": [
              "x",
              "y",
              "z"
            ],
            "additionalProperties": false
          },
          {
            "type": "null"
          }
        ]
      },
      "victimPosition": {
        "type": "object",
        "properties": {
          "x": {
            "type": "integer",
            "minimum": -9007199254740991,
            "maximum": 9007199254740991
          },
          "y": {
            "type": "integer",
            "minimum": -9007199254740991,
            "maximum": 9007199254740991
          },
          "z": {
            "type": "integer",
            "minimum": -9007199254740991,
            "maximum": 9007199254740991
          }
        },
        "required": [
          "x",
          "y",
          "z"
        ],
        "additionalProperties": false
      }
    },
    "required": [
      "roundNumber",
      "tick",
      "attackerIndex",
      "victimIndex",
      "weapon",
      "hitgroup",
      "healthDamage",
      "healthDamageRaw",
      "armorDamage",
      "victimHealthBefore",
      "victimArmorAfter",
      "attackerPosition",
      "victimPosition"
    ],
    "additionalProperties": false
  }
}

=== Starfie1d1272/cs2-demo-format/fixtures/v3-mid/damages.json
[{"roundNumber":1,"tick":5429,"attackerIndex":5,"victimIndex":1,"weapon":"usp_silencer","hitgroup":"chest","healthDamage":16,"healthDamageRaw":16,"armorDamage":8,"victimHealthBefore":100,"victimArmorAfter":92,"attackerPosition":{"x":243,"y":404,"z":-15},"victimPosition":{"x":288,"y":218,"z":-189}},{"roundNumber":1,"tick":5430,"attackerIndex":1,"victimIndex":5,"weapon":"glock","hitgroup":"chest","healthDamage":27,"healthDamageRaw":27,"armorDamage":0,"victimHealthBefore":100,"victimArmorAfter":0,"attackerPosition":{"x":285,"y":219,"z":-189},"victimPosition":{"x":244,"y":403,"z":-15}},{"roundNumber":1,"tick":5440,"attackerIndex":5,"victimIndex":1,"weapon":"usp_silencer","hitgroup":"head","healthDamage":84,"healthDamageRaw":133,"armorDamage":0,"victimHealthBefore":84,"victimArmorAfter":92,"attackerPosition":{"x":243,"y":407,"z":-15},"victimPosition":{"x":268,"y":224,"z":-189}},{"roundNumber":1,"tick":5619,"attackerIndex":0,"victimIndex":9,"weapon":"p250","hitgroup":"head","healthDamage":100,"healthDamageRaw":111,"armorDamage":0,"victimHealthBefore":100,"victimArmorAfter":100,"attackerPosition":{"x":692,"y":78,"z":-152},"victimPosition":{"x":-772,"y":131,"z":-96}},{"roundNumber":1,"tick":5856,"attackerIndex":3,"victimIndex":7,"weapon":"glock","hitgroup":"head","healthDamage":96,"healthDamageRaw":96,"armorDamage":0,"victimHealthBefore":100,"victimArmorAfter":100,"attackerPosition":{"x":-1735,"y":110,"z":2},"victimPosition":{"x":-1280,"y":669,"z":0}},{"roundNumber":1,"tick":5866,"attackerIndex":3,"victimIndex":7,"weapon":"glock","hitgroup":"head","healthDamage":4,"healthDamageRaw":95,"armorDamage":0,"victimHealthBefore":4,"victimArmorAfter":100,"attackerPosition":{"x":-1761,"y":132,"z":3},"victimPosition":{"x":-1268,"y":682,"z":0}},{"roundNumber":1,"tick":6284,"attackerIndex":4,"victimIndex":8,"weapon":"glock","hitgroup":"chest","healthDamage":10,"healthDamageRaw":10,"armorDamage":5,"victimHealthBefore":100,"victimArmorAfter":95,"attackerPosition":{"x":-1536,"y":536,"z":0},"victimPosition":{"x":-750,"y":1165,"z":32}},{"roundNumber":1,"tick":6294,"attackerIndex":4,"victimIndex":8,"weapon":"glock","hitgroup":"chest","healthDamage":10,"healthDamageRaw":10,"armorDamage":5,"victimHealthBefore":90,"victimArmorAfter":90,"attackerPosition":{"x":-1547,"y":562,"z":19},"victimPosition":{"x":-743,"y":1157,"z":32}},{"roundNumber":1,"tick":6296,"attackerIndex":8,"victimIndex":4,"weapon":"usp_silencer","hitgroup":"stomach","healthDamage":36,"healthDamageRaw":36,"armorDamage":0,"victimHealthBefore":100,"victimArmorAfter":0,"attackerPosition":{"x":-741,"y":1155,"z":32},"victimPosition":{"x":-1547,"y":563,"z":19}},{"roundNumber":1,"tick":6926,"attackerIndex":8,"victimIndex":4,"weapon":"usp_silencer","hitgroup":"head","healthDamage":64,"healthDamageRaw":119,"armorDamage":0,"victimHealthBefore":64,"victimArmorAfter":0,"attackerPosition":{"x":-993,"y":1149,"z":35},"victimPosition":{"x":-850,"y":325,"z":-56}},{"roundNumber":1,"tick":6950,"attackerIndex":6,"victimIndex":5,"weapon":"usp_silencer","hitgroup":"head","healthDamage":44,"healthDamageRaw":44,"armorDamage":0,"victimHealthBefore":73,"victimArmorAfter":0,"attackerPosition":{"x":-1333,"y":1219,"z":1},"victimPosition":{"x":-1214,"y":1139,"z":1}},{"roundNumber":1,"tick":7240,"attackerIndex":3,"victimIndex":6,"weapon":"glock","hitgroup":"chest","healthDamage":11,"healthDamageRaw":11,"armorDamage":6,"victimHealthBefore":100,"victimArmorAfter":94,"attackerPosition":{"x":-1531,"y":759,"z":38},"victimPosition":{"x":-975,"y":844,"z":18}},{"roundNumber":1,"tick":7249,"attackerIndex":3,"victimIndex":6,"weapon":"glock","hitgroup":"chest","healthDamage":11,"healthDamageRaw":11,"armorDamage":6,"victimHealthBefore":89,"victimArmorAfter":88,"attackerPosition":{"x":-1529,"y":749,"z":38},"victimPosition":{"x":-970,"y":830,"z":14}},{"roundNumber":1,"tick":7270,"attackerIndex":3,"victimIndex":6,"weapon":"glock","hitgroup":"head","healthDamage":78,"healthDamageRaw":100,"armorDamage":0,"victimHealthBefore":78,"victimArmorAfter":88,"attackerPosition":{"x":-1529,"y":749,"z":38},"victimPosition":{"x":-977,"y":828,"z":10}},{"roundNumber":1,"tick":7300,"attackerIndex":3,"victimIndex":8,"weapon":"glock","hitgroup":"stomach","healthDamage":13,"healthDamageRaw":13,"armorDamage":7,"victimHealthBefore":80,"victimArmorAfter":83,"attackerPosition":{"x":-1533,"y":778,"z":38},"victimPosition":{"x":-802,"y":844,"z":35}},{"roundNumber":1,"tick":7313,"attackerIndex":5,"victimIndex":2,"weapon":"smokegrenade","hitgroup":"generic","healthDamage":1,"healthDamageRaw":1,"armorDamage":0,"victimHealthBefore":100,"victimArmorAfter":100,"attackerPosition":{"x":-1199,"y":873,"z":0},"victimPosition":{"x":-1630,"y":194,"z":1}},{"roundNumber":1,"tick":7319,"attackerIndex":3,"victimIndex":8,"weapon":"glock","hitgroup":"chest","healthDamage":11,"healthDamageRaw":11,"armorDamage":6,"victimHealthBefore":67,"victimArmorAfter":77,"attackerPosition":{"x":-1531,"y":769,"z":38},"victimPosition":{"x":-781,"y":814,"z":35}},{"roundNumber":1,"tick":7355,"attackerIndex":8,"victimIndex":3,"weapon":"usp_silencer","hitgroup":"chest","healthDamage":15,"healthDamageRaw":15,"armorDamage":7,"victimHealthBefore":100,"victimArmorAfter":93,"attackerPosition":{"x":-780,"y":815,"z":35},"victimPosition":{"x":-1543,"y":702,"z":38}},{"roundNumber":1,"tick":7367,"attackerIndex":5,"victimIndex":3,"weapon":"usp_silencer","hitgroup":"head","healthDamage":85,"healthDamageRaw":129,"armorDamage":0,"victimHealthBefore":85,"victimArmorAfter":93,"attackerPosition":{"x":-1145,"y":795,"z":-4},"victimPosition":{"x":-1550,"y":687,"z":40}},{"roundNumber":1,"tick":7437,"attackerIndex":0,"victimIndex":8,"weapon":"p250","hitgroup":"chest","healthDamage":22,"healthDamageRaw":22,"armorDamage":6,"victimHealthBefore":56,"victimArmorAfter":71,"attackerPosition":{"x":-1030,"y":427,"z":-5},"victimPosition":{"x":-723,"y":731,"z":38}},{"roundNumber":1,"tick":7453,"attackerIndex":5,"victimIndex":2,"weapon":"usp_silencer","hitgroup":"chest","healthDamage":16,"healthDamageRaw":16,"armorDamage":7,"victimHealthBefore":99,"victimArmorAfter":93,"attackerPosition":{"x":-1129,"y":840,"z":0},"victimPosition":{"x":-1390,"y":421,"z":0}},{"roundNumber":1,"tick":7458,"attackerIndex":2,"victimIndex":5,"weapon":"glock","hitgroup":"chest","healthDamage":25,"healthDamageRaw":25,"armorDamage":0,"victimHealthBefore":29,"victimArmorAfter":0,"attackerPosition":{"x":-1378,"y":425,"z":0},"victimPosition":{"x":-1122,"y":835,"z":-1}},{"roundNumber":1,"tick":7578,"attackerIndex":8,"victimIndex":0,"weapon":"usp_silencer","hitgroup":"head","healthDamage":100,"healthDamageRaw":131,"armorDamage":0,"victimHealthBefore":100,"victimArmorAfter":100,"attackerPosition":{"x":-707,"y":643,"z":38},"victimPosition":{"x":-1023,"y":500,"z":0}},{"roundNumber":1,"tick":7613,"attackerIndex":8,"victimIndex":2,"weapon":"usp_silencer","hitgroup":"chest","healthDamage":16,"healthDamageRaw":16,"armorDamage":7,"victimHealthBefore":83,"victimArmorAfter":86,"attackerPosition":{"x":-707,"y":641,"z":38},"victimPosition":{"x":-1193,"y":510,"z":0}},{"roundNumber":1,"tick":7668,"attackerIndex":8,"victimIndex":2,"weapon":"usp_silencer","hitgroup":"chest","healthDamage":15,"healthDamageRaw":15,"armorDamage":7,"victimHealthBefore":67,"victimArmorAfter":79,"attackerPosition":{"x":-709,"y":647,"z":38},"victimPosition":{"x":-1258,"y":560,"z":0}},{"roundNumber":1,"tick":7678,"attackerIndex":2,"victimIndex":8,"weapon":"glock","hitgroup":"chest","healthDamage":11,"healthDamageRaw":11,"armorDamage":6,"victimHealthBefore":34,"victimArmorAfter":65,"attackerPosition":{"x":-1258,"y":560,"z":0},"victimPosition":{"x":-709,"y":651,"z":38}},{"roundNumber":1,"tick":7688,"attackerIndex":2,"victimIndex":8,"weapon":"glock","hitgroup":"chest","healthDamage":11,"healthDamageRaw":11,"armorDamage":6,"victimHealthBefore":23,"victimArmorAfter":59,"attackerPosition":{"x":-1260,"y":574,"z":0},"victimPosition":{"x":-710,"y":655,"z":38}},{"roundNumber":1,"tick":7703,"attackerIndex":5,"victimIndex":2,"weapon":"usp_silencer","hitgroup":"chest","healthDamage":16,"healthDamageRaw":16,"armorDamage":8,"victimHealthBefore":52,"victimArmorAfter":71,"attackerPosition":{"x":-896,"y":565,"z":-4},"victimPosition":{"x":-1271,"y":596,"z":0}},{"roundNumber":1,"tick":7716,"attackerIndex":2,"victimIndex":5,"weapon":"glock","hitgroup":"stomach","healthDamage":4,"healthDamageRaw":33,"armorDamage":0,"victimHealthBefore":4,"victimArmorAfter":0,"attackerPosition":{"x":-1278,"y":610,"z":0},"victimPosition":{"x":-898,"y":566,"z":-4}},{"roundNumber":1,"tick":8079,"attackerIndex":8,"victimIndex":2,"weapon":"usp_silencer","hitgroup":"chest","healthDamage":17,"healthDamageRaw":17,"armorDamage":8,"victimHealthBefore":36,"victimArmorAfter":63,"attackerPosition":{"x":-898,"y":608,"z":-4},"victimPosition":{"x":-1088,"y":583,"z":-4}},{"roundNumber":1,"tick":8103,"attackerIndex":2,"victimIndex":8,"weapon":"glock","hitgroup":"chest","healthDamage":12,"healthDamageRaw":13,"armorDamage":7,"victimHealthBefore":12,"victimArmorAfter":52,"attackerPosition":{"x":-1088,"y":600,"z":-2},"victimPosition":{"x":-896,"y":607,"z":-4}},{"roundNumber":2,"tick":11102,"attackerIndex":5,"victimIndex":0,"weapon":"usp_silencer","hitgroup":"right_arm","healthDamage":13,"healthDamageRaw":13,"armorDamage":6,"victimHealthBefore":100,"victimArmorAfter":94,"attackerPosition":{"x":-719,"y":173,"z":-96},"victimPosition":{"x":814,"y":12,"z":-152}},{"roundNumber":2,"tick":12337,"attackerIndex":4,"victimIndex":5,"weapon":"mac10","hitgroup":"chest","healthDamage":24,"healthDamageRaw":24,"armorDamage":0,"victimHealthBefore":100,"victimArmorAfter":0,"attackerPosition":{"x":796,"y":158,"z":-146},"victimPosition":{"x":411,"y":239,"z":-189}},{"roundNumber":2,"tick":12342,"attackerIndex":4,"victimIndex":5,"weapon":"mac10","hitgroup":"chest","healthDamage":24,"healthDamageRaw":24,"armorDamage":0,"victimHealthBefore":76,"victimArmorAfter":0,"attackerPosition":{"x":798,"y":176,"z":-146},"victimPosition":{"x":417,"y":240,"z":-189}},{"roundNumber":2,"tick"
