=== Starfie1d1272/cs2-demo-format/spec/grenades.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "roundNumber": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "grenadeId": {
        "type": [
          "string",
          "null"
        ]
      },
      "throwTick": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "effectTick": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "destroyTick": {
        "anyOf": [
          {
            "type": "integer",
            "minimum": 1,
            "maximum": 9007199254740991
          },
          {
            "type": "null"
          }
        ]
      },
      "grenade": {
        "type": "string",
        "enum": [
          "flashbang",
          "smoke",
          "molotov",
          "incendiary",
          "hegrenade",
          "decoy"
        ]
      },
      "throwerIndex": {
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      },
      "throwPosition": {
        "type": "object",
        "properties": {
          "x": {
            "type": "integer",
            "minimum": -9007199254740991,
            "maximum": 9007199254740991
          },
          "y": {
            "type": "integer",
            "minimum": -9007199254740991,
            "maximum": 9007199254740991
          },
          "z": {
            "type": "integer",
            "minimum": -9007199254740991,
            "maximum": 9007199254740991
          }
        },
        "required": [
          "x",
          "y",
          "z"
        ],
        "additionalProperties": false
      },
      "effectPosition": {
        "type": "object",
        "properties": {
          "x": {
            "type": "integer",
            "minimum": -9007199254740991,
            "maximum": 9007199254740991
          },
          "y": {
            "type": "integer",
            "minimum": -9007199254740991,
            "maximum": 9007199254740991
          },
          "z": {
            "type": "integer",
            "minimum": -9007199254740991,
            "maximum": 9007199254740991
          }
        },
        "required": [
          "x",
          "y",
          "z"
        ],
        "additionalProperties": false
      }
    },
    "required": [
      "roundNumber",
      "grenadeId",
      "throwTick",
      "effectTick",
      "destroyTick",
      "grenade",
      "throwerIndex",
      "throwPosition",
      "effectPosition"
    ],
    "additionalProperties": false
  }
}

=== Starfie1d1272/cs2-demo-format/fixtures/v3-mid/grenades.json
[{"roundNumber":1,"grenadeId":"273-5815","throwTick":5815,"effectTick":6163,"destroyTick":7575,"grenade":"smoke","throwerIndex":4,"throwPosition":{"x":-1265,"y":-298,"z":89},"effectPosition":{"x":-1282,"y":974,"z":2}},{"roundNumber":1,"grenadeId":"175-7198","throwTick":7198,"effectTick":7330,"destroyTick":null,"grenade":"smoke","throwerIndex":5,"throwPosition":{"x":-1125,"y":979,"z":83},"effectPosition":{"x":-1621,"y":216,"z":3}},{"roundNumber":2,"grenadeId":"301-9974","throwTick":9974,"effectTick":10337,"destroyTick":11749,"grenade":"smoke","throwerIndex":3,"throwPosition":{"x":-412,"y":-1699,"z":105},"effectPosition":{"x":-99,"y":771,"z":2}},{"roundNumber":2,"grenadeId":"292-12522","throwTick":12522,"effectTick":12714,"destroyTick":null,"grenade":"smoke","throwerIndex":1,"throwPosition":{"x":1238,"y":818,"z":-60},"effectPosition":{"x":574,"y":1327,"z":-78}},{"roundNumber":3,"grenadeId":"169-15304","throwTick":15304,"effectTick":15481,"destroyTick":16893,"grenade":"smoke","throwerIndex":5,"throwPosition":{"x":203,"y":1199,"z":40},"effectPosition":{"x":-44,"y":-22,"z":2}},{"roundNumber":3,"grenadeId":"104-15146","throwTick":15146,"effectTick":15509,"destroyTick":16921,"grenade":"smoke","throwerIndex":3,"throwPosition":{"x":-413,"y":-1699,"z":105},"effectPosition":{"x":-97,"y":771,"z":2}},{"roundNumber":3,"grenadeId":"326-15401","throwTick":15401,"effectTick":15550,"destroyTick":16962,"grenade":"smoke","throwerIndex":8,"throwPosition":{"x":-938,"y":1045,"z":101},"effectPosition":{"x":-1704,"y":183,"z":3}},{"roundNumber":3,"grenadeId":"322-15377","throwTick":15377,"effectTick":15815,"destroyTick":17227,"grenade":"smoke","throwerIndex":1,"throwPosition":{"x":816,"y":-752,"z":92},"effectPosition":{"x":-597,"y":161,"z":-94}},{"roundNumber":3,"grenadeId":"158-16033","throwTick":16033,"effectTick":16177,"destroyTick":17589,"grenade":"smoke","throwerIndex":7,"throwPosition":{"x":1614,"y":1474,"z":-83},"effectPosition":{"x":1303,"y":815,"z":-150}},{"roundNumber":3,"grenadeId":"72-18159","throwTick":18159,"effectTick":18288,"destroyTick":19700,"grenade":"smoke","throwerIndex":9,"throwPosition":{"x":-684,"y":381,"z":0},"effectPosition":{"x":-504,"y":154,"z":-118}},{"roundNumber":3,"grenadeId":"175-19161","throwTick":19161,"effectTick":19329,"destroyTick":20741,"grenade":"smoke","throwerIndex":1,"throwPosition":{"x":-44,"y":810,"z":75},"effectPosition":{"x":62,"y":1607,"z":-28}},{"roundNumber":4,"grenadeId":"124-25928","throwTick":25928,"effectTick":26363,"destroyTick":27775,"grenade":"smoke","throwerIndex":9,"throwPosition":{"x":-550,"y":2175,"z":136},"effectPosition":{"x":823,"y":-138,"z":-94}},{"roundNumber":4,"grenadeId":"423-26271","throwTick":26271,"effectTick":26372,"destroyTick":27784,"grenade":"smoke","throwerIndex":7,"throwPosition":{"x":-1208,"y":915,"z":62},"effectPosition":{"x":-1566,"y":255,"z":2}},{"roundNumber":4,"grenadeId":"98-26196","throwTick":26196,"effectTick":26556,"destroyTick":27968,"grenade":"smoke","throwerIndex":3,"throwPosition":{"x":-415,"y":-1699,"z":105},"effectPosition":{"x":-90,"y":745,"z":2}},{"roundNumber":4,"grenadeId":"418-27788","throwTick":27788,"effectTick":27928,"destroyTick":29340,"grenade":"smoke","throwerIndex":6,"throwPosition":{"x":509,"y":262,"z":-118},"effectPosition":{"x":726,"y":-20,"z":-136}},{"roundNumber":5,"grenadeId":"303-31953","throwTick":31953,"effectTick":32313,"destroyTick":33725,"grenade":"smoke","throwerIndex":3,"throwPosition":{"x":-414,"y":-1699,"z":105},"effectPosition":{"x":-95,"y":746,"z":2}},{"roundNumber":5,"grenadeId":"327-31774","throwTick":31774,"effectTick":32322,"destroyTick":33734,"grenade":"smoke","throwerIndex":9,"throwPosition":{"x":-466,"y":2198,"z":136},"effectPosition":{"x":254,"y":950,"z":-32}},{"roundNumber":5,"grenadeId":"472-32170","throwTick":32170,"effectTick":32552,"destroyTick":33964,"grenade":"smoke","throwerIndex":1,"throwPosition":{"x":816,"y":-752,"z":92},"effectPosition":{"x":-535,"y":125,"z":-118}},{"roundNumber":5,"grenadeId":"212-33537","throwTick":33537,"effectTick":33693,"destroyTick":35105,"grenade":"smoke","throwerIndex":5,"throwPosition":{"x":1240,"y":822,"z":-78},"effectPosition":{"x":794,"y":-237,"z":-94}},{"roundNumber":5,"grenadeId":"128-33771","throwTick":33771,"effectTick":33911,"destroyTick":35323,"grenade":"smoke","throwerIndex":9,"throwPosition":{"x":100,"y":1572,"z":38},"effectPosition":{"x":182,"y":901,"z":-31}},{"roundNumber":5,"grenadeId":"210-33920","throwTick":33920,"effectTick":34039,"destroyTick":35451,"grenade":"smoke","throwerIndex":7,"throwPosition":{"x":-978,"y":420,"z":51},"effectPosition":{"x":-1646,"y":262,"z":2}},{"roundNumber":5,"grenadeId":"239-35815","throwTick":35815,"effectTick":35913,"destroyTick":37325,"grenade":"smoke","throwerIndex":0,"throwPosition":{"x":-1566,"y":96,"z":64},"effectPosition":{"x":-1399,"y":465,"z":2}},{"roundNumber":5,"grenadeId":"102-37128","throwTick":37128,"effectTick":37479,"destroyTick":38891,"grenade":"smoke","throwerIndex":4,"throwPosition":{"x":-1265,"y":-298,"z":89},"effectPosition":{"x":-1277,"y":961,"z":2}},{"roundNumber":5,"grenadeId":"182-38029","throwTick":38029,"effectTick":38153,"destroyTick":null,"grenade":"smoke","throwerIndex":2,"throwPosition":{"x":-1602,"y":234,"z":73},"effectPosition":{"x":-778,"y":1156,"z":34}},{"roundNumber":6,"grenadeId":"180-41499","throwTick":41499,"effectTick":41663,"destroyTick":43075,"grenade":"smoke","throwerIndex":5,"throwPosition":{"x":234,"y":1298,"z":40},"effectPosition":{"x":-104,"y":-17,"z":2}},{"roundNumber":6,"grenadeId":"240-41633","throwTick":41633,"effectTick":41733,"destroyTick":43145,"grenade":"smoke","throwerIndex":7,"throwPosition":{"x":-1224,"y":898,"z":62},"effectPosition":{"x":-1577,"y":225,"z":2}},{"roundNumber":6,"grenadeId":"206-41402","throwTick":41402,"effectTick":41767,"destroyTick":43179,"grenade":"smoke","throwerIndex":3,"throwPosition":{"x":-412,"y":-1699,"z":105},"effectPosition":{"x":-103,"y":774,"z":2}},{"roundNumber":6,"grenadeId":"460-42838","throwTick":42838,"effectTick":42994,"destroyTick":44406,"grenade":"smoke","throwerIndex":6,"throwPosition":{"x":-831,"y":1107,"z":103},"effectPosition":{"x":-1649,"y":279,"z":2}},{"roundNumber":6,"grenadeId":"456-43793","throwTick":43793,"effectTick":43814,"destroyTick":45226,"grenade":"smoke","throwerIndex":8,"throwPosition":{"x":-894,"y":363,"z":17},"effectPosition":{"x":-784,"y":289,"z":-54}},{"roundNumber":6,"grenadeId":"121-44548","throwTick":44548,"effectTick":44663,"destroyTick":46075,"grenade":"smoke","throwerIndex":9,"throwPosition":{"x":1181,"y":2035,"z":-122},"effectPosition":{"x":1692,"y":1295,"z":-150}},{"roundNumber":6,"grenadeId":"316-45136","throwTick":45136,"effectTick":45273,"destroyTick":null,"grenade":"smoke","throwerIndex":2,"throwPosition":{"x":-1637,"y":117,"z":68},"effectPosition":{"x":-1134,"y":1121,"z":2}},{"roundNumber":7,"grenadeId":"412-51118","throwTick":51118,"effectTick":51226,"destroyTick":52638,"grenade":"smoke","throwerIndex":8,"throwPosition":{"x":-1195,"y":928,"z":56},"effectPosition":{"x":-1530,"y":388,"z":2}},{"roundNumber":7,"grenadeId":"371-52198","throwTick":52198,"effectTick":52368,"destroyTick":53780,"grenade":"smoke","throwerIndex":5,"throwPosition":{"x":944,"y":2154,"z":29},"effectPosition":{"x":1630,"y":1219,"z":-150}},{"roundNumber":7,"grenadeId":"319-52241","throwTick":52241,"effectTick":52401,"destroyTick":53813,"grenade":"smoke","throwerIndex":7,"throwPosition":{"x":-958,"y":1059,"z":103},"effectPosition":{"x":-1768,"y":112,"z":5}},{"roundNumber":7,"grenadeId":"309-52329","throwTick":52329,"effectTick":52446,"destroyTick":53858,"grenade":"smoke","throwerIndex":9,"throwPosition":{"x":-1593,"y":680,"z":102},"effectPosition":{"x":-1669,"y":353,"z":2}},{"roundNumber":7,"grenadeId":"184-52293","throwTick":52293,"effectTick":52470,"destroyTick":53882,"grenade":"smoke","throwerIndex":3,"throwPosition":{"x":1270,"y":592,"z":74},"effectPosition":{"x":594,"y":1245,"z":-86}},{"roundNumber":7,"grenadeId":"415-52621","throwTick":52621,"effectTick":52839,"destroyTick":54251,"grenade":"smoke","throwerIndex":1,"throwPosition":{"x":1238,"y":818,"z":-60},"effectPosition":{"x":579,"y":1325,"z":-86}},{"roundNumber":7,"grenadeId":"182-53826","throwTick":53826,"effectTick":53938,"destroyTick":55350,"grenade":"smoke","throwerIndex":7,"throwPosition":{"x":848,"y":1531,"z":-21},"effectPosition":{"x":568,"y":1389,"z":-78}},{"roundNumber":8,"grenadeId":"265-58106","throwTick":58106,"effectTick":58208,"destroyTick":59620,"grenade":"smoke","throwerIndex":9,"throwPosition":{"x":-1210,"y":962,"z":66},"effectPosition":{"x":-1646,"y":246,"z":3}},{"roundNumber":8,"grenadeId":"67-58010","throwTick":58010,"effectTick":58376,"destroyTick":59788,"grenade":"smoke","throwerIndex":3,"throwPosition":{"x":-416,"y":-1699,"z":105},"effectPosition":{"x":-76,"y":770,"z":2}},{"roundNumber":8,"grenadeId":"377-59388","throwTick":59388,"effectTick":59499,"destroyTick":60911,"grenade":"smoke","throwerIndex":7,"throwPosition":{"x":1089,"y":1874,"z":-122},"effectPosition":{"x":1735,"y":1329,"z":-150}},{"roundNumber":8,"grenadeId":"268-59504","throwTick":59504,"effectTick":59599,"destroyTick":61011,"grenade":"smoke","throwerIndex":5,"throwPosition":{"x":-740,"y":297,"z":4},"effectPosition":{"x":-331,"y":104,"z":-118}},{"roundNumber":8,"grenadeId":"232-59481","throwTick":59481,"effectTick":59613,"destroyTick":61025,"grenade":"smoke","throwerIndex":8,"throwPosition":{"x":-898,"y":634,"z":67},"effectPosition":{"x":-1631,"y":367,"z":2}},{"roundNumber":8,"grenadeId":"473-59688","throwTick":59688,"effectTick":59821,"destroyTick":61233,"grenade":"smoke","throwerIndex":6,"throwPosition":{"x":124,"y":1567,"z":35},"effectPosition":{"x":212,"y":696,"z":-32}},{"roundNumber":8,"grenadeId":"280-60377","throwTick":60377,"effectTick":60514,"destroyTick":61926,"grenade":"smoke","throwerIndex":1,"throwPosition":{"x":-54,"y":798,"z":74},"effectPosition":{"x":227,"y":1514,"z":-30}},{"roundNumber":8,"grenadeId":"376-60559","throwTick":60559,"effectTick":60882,"destroyTick":622
