=== Starfie1d1272/cs2-demo-format/spec/kills.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "roundNumber": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "tick": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "killerIndex": {
        "anyOf": [
          {
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          {
            "type": "null"
          }
        ]
      },
      "victimIndex": {
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      },
      "assisterIndex": {
        "anyOf": [
          {
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          {
            "type": "null"
          }
        ]
      },
      "flashAssisterIndex": {
        "anyOf": [
          {
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          {
            "type": "null"
          }
        ]
      },
      "weapon": {
        "type": "string",
        "minLength": 1
      },
      "killerActiveWeapon": {
        "type": [
          "string",
          "null"
        ]
      },
      "victimActiveWeapon": {
        "type": [
          "string",
          "null"
        ]
      },
      "headshot": {
        "type": "boolean"
      },
      "flashAssist": {
        "type": "boolean"
      },
      "tradeKill": {
        "type": "boolean"
      },
      "tradeDeath": {
        "type": "boolean"
      },
      "throughSmoke": {
        "type": "boolean"
      },
      "noScope": {
        "type": "boolean"
      },
      "penetratedObjects": {
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      },
      "killerPosition": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "x": {
                "type": "integer",
                "minimum": -9007199254740991,
                "maximum": 9007199254740991
              },
              "y": {
                "type": "integer",
                "minimum": -9007199254740991,
                "maximum": 9007199254740991
              },
              "z": {
                "type": "integer",
                "minimum": -9007199254740991,
                "maximum": 9007199254740991
              }
            },
            "required": [
              "x",
              "y",
              "z"
            ],
            "additionalProperties": false
          },
          {
            "type": "null"
          }
        ]
      },
      "victimPosition": {
        "type": "object",
        "properties": {
          "x": {
            "type": "integer",
            "minimum": -9007199254740991,
            "maximum": 9007199254740991
          },
          "y": {
            "type": "integer",
            "minimum": -9007199254740991,
            "maximum": 9007199254740991
          },
          "z": {
            "type": "integer",
            "minimum": -9007199254740991,
            "maximum": 9007199254740991
          }
        },
        "required": [
          "x",
          "y",
          "z"
        ],
        "additionalProperties": false
      }
    },
    "required": [
      "roundNumber",
      "tick",
      "killerIndex",
      "victimIndex",
      "assisterIndex",
      "flashAssisterIndex",
      "weapon",
      "killerActiveWeapon",
      "victimActiveWeapon",
      "headshot",
      "flashAssist",
      "tradeKill",
      "tradeDeath",
      "throughSmoke",
      "noScope",
      "penetratedObjects",
      "killerPosition",
      "victimPosition"
    ],
    "additionalProperties": false
  }
}

=== Starfie1d1272/cs2-demo-format/fixtures/v3-mid/kills.json
[{"roundNumber":1,"tick":5440,"killerIndex":5,"victimIndex":1,"assisterIndex":null,"flashAssisterIndex":null,"weapon":"usp_silencer","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":true,"flashAssist":false,"tradeKill":false,"tradeDeath":false,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":243,"y":407,"z":-15},"victimPosition":{"x":268,"y":224,"z":-189}},{"roundNumber":1,"tick":5619,"killerIndex":0,"victimIndex":9,"assisterIndex":null,"flashAssisterIndex":null,"weapon":"p250","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":true,"flashAssist":false,"tradeKill":false,"tradeDeath":false,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":692,"y":78,"z":-152},"victimPosition":{"x":-772,"y":131,"z":-96}},{"roundNumber":1,"tick":5866,"killerIndex":3,"victimIndex":7,"assisterIndex":null,"flashAssisterIndex":null,"weapon":"glock","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":true,"flashAssist":false,"tradeKill":false,"tradeDeath":false,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":-1761,"y":132,"z":3},"victimPosition":{"x":-1268,"y":682,"z":0}},{"roundNumber":1,"tick":6926,"killerIndex":8,"victimIndex":4,"assisterIndex":null,"flashAssisterIndex":null,"weapon":"usp_silencer","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":true,"flashAssist":false,"tradeKill":false,"tradeDeath":false,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":-993,"y":1149,"z":35},"victimPosition":{"x":-850,"y":325,"z":-56}},{"roundNumber":1,"tick":7270,"killerIndex":3,"victimIndex":6,"assisterIndex":null,"flashAssisterIndex":null,"weapon":"glock","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":true,"flashAssist":false,"tradeKill":false,"tradeDeath":true,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":-1529,"y":749,"z":38},"victimPosition":{"x":-977,"y":828,"z":10}},{"roundNumber":1,"tick":7367,"killerIndex":5,"victimIndex":3,"assisterIndex":null,"flashAssisterIndex":null,"weapon":"usp_silencer","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":true,"flashAssist":false,"tradeKill":true,"tradeDeath":true,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":-1145,"y":795,"z":-4},"victimPosition":{"x":-1550,"y":687,"z":40}},{"roundNumber":1,"tick":7578,"killerIndex":8,"victimIndex":0,"assisterIndex":null,"flashAssisterIndex":null,"weapon":"usp_silencer","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":true,"flashAssist":false,"tradeKill":false,"tradeDeath":false,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":-707,"y":643,"z":38},"victimPosition":{"x":-1023,"y":500,"z":0}},{"roundNumber":1,"tick":7716,"killerIndex":2,"victimIndex":5,"assisterIndex":6,"flashAssisterIndex":null,"weapon":"glock","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":false,"flashAssist":false,"tradeKill":true,"tradeDeath":false,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":-1278,"y":610,"z":0},"victimPosition":{"x":-898,"y":566,"z":-4}},{"roundNumber":1,"tick":8103,"killerIndex":2,"victimIndex":8,"assisterIndex":null,"flashAssisterIndex":null,"weapon":"glock","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":false,"flashAssist":false,"tradeKill":false,"tradeDeath":false,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":-1088,"y":600,"z":-2},"victimPosition":{"x":-896,"y":607,"z":-4}},{"roundNumber":2,"tick":12366,"killerIndex":4,"victimIndex":5,"assisterIndex":null,"flashAssisterIndex":null,"weapon":"mac10","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":false,"flashAssist":false,"tradeKill":false,"tradeDeath":false,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":798,"y":184,"z":-146},"victimPosition":{"x":424,"y":259,"z":-189}},{"roundNumber":2,"tick":12963,"killerIndex":4,"victimIndex":7,"assisterIndex":0,"flashAssisterIndex":null,"weapon":"mac10","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":false,"flashAssist":false,"tradeKill":false,"tradeDeath":false,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":1435,"y":1722,"z":-152},"victimPosition":{"x":830,"y":1547,"z":-88}},{"roundNumber":2,"tick":13015,"killerIndex":2,"victimIndex":9,"assisterIndex":4,"flashAssisterIndex":null,"weapon":"ak47","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":false,"flashAssist":false,"tradeKill":false,"tradeDeath":false,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":1663,"y":1934,"z":-84},"victimPosition":{"x":941,"y":1323,"z":-88}},{"roundNumber":2,"tick":13151,"killerIndex":6,"victimIndex":0,"assisterIndex":7,"flashAssisterIndex":null,"weapon":"usp_silencer","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":false,"flashAssist":false,"tradeKill":false,"tradeDeath":true,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":893,"y":2114,"z":-40},"victimPosition":{"x":1200,"y":2132,"z":-139}},{"roundNumber":2,"tick":13227,"killerIndex":1,"victimIndex":8,"assisterIndex":4,"flashAssisterIndex":null,"weapon":"galilar","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":true,"flashAssist":false,"tradeKill":false,"tradeDeath":false,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":1156,"y":1538,"z":-152},"victimPosition":{"x":795,"y":1345,"z":-88}},{"roundNumber":2,"tick":13328,"killerIndex":1,"victimIndex":6,"assisterIndex":2,"flashAssisterIndex":null,"weapon":"galilar","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":false,"flashAssist":false,"tradeKill":true,"tradeDeath":false,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":1151,"y":1618,"z":-150},"victimPosition":{"x":1010,"y":2258,"z":-40}},{"roundNumber":3,"tick":18171,"killerIndex":5,"victimIndex":2,"assisterIndex":null,"flashAssisterIndex":null,"weapon":"m4a1_silencer","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":false,"flashAssist":false,"tradeKill":false,"tradeDeath":false,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":10,"y":883,"z":0},"victimPosition":{"x":-231,"y":-200,"z":0}},{"roundNumber":3,"tick":19362,"killerIndex":5,"victimIndex":4,"assisterIndex":null,"flashAssisterIndex":null,"weapon":"m4a1_silencer","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":false,"flashAssist":false,"tradeKill":false,"tradeDeath":false,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":524,"y":1360,"z":-37},"victimPosition":{"x":-68,"y":731,"z":0}},{"roundNumber":3,"tick":19891,"killerIndex":3,"victimIndex":7,"assisterIndex":null,"flashAssisterIndex":null,"weapon":"ak47","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":true,"flashAssist":false,"tradeKill":false,"tradeDeath":false,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":1061,"y":1370,"z":-88},"victimPosition":{"x":1127,"y":1985,"z":-192}},{"roundNumber":3,"tick":20012,"killerIndex":1,"victimIndex":5,"assisterIndex":4,"flashAssisterIndex":null,"weapon":"galilar","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":true,"flashAssist":false,"tradeKill":false,"tradeDeath":false,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":760,"y":1302,"z":-88},"victimPosition":{"x":833,"y":1977,"z":-40}},{"roundNumber":3,"tick":20967,"killerIndex":3,"victimIndex":6,"assisterIndex":1,"flashAssisterIndex":null,"weapon":"ak47","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":true,"flashAssist":false,"tradeKill":false,"tradeDeath":true,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":975,"y":2177,"z":-40},"victimPosition":{"x":812,"y":2016,"z":-40}},{"roundNumber":3,"tick":21043,"killerIndex":8,"victimIndex":3,"assisterIndex":null,"flashAssisterIndex":null,"weapon":"m4a1_silencer","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":true,"flashAssist":false,"tradeKill":true,"tradeDeath":true,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":753,"y":1825,"z":-40},"victimPosition":{"x":889,"y":2176,"z":-40}},{"roundNumber":3,"tick":21143,"killerIndex":1,"victimIndex":9,"assisterIndex":null,"flashAssisterIndex":null,"weapon":"galilar","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":true,"flashAssist":false,"tradeKill":false,"tradeDeath":false,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":1516,"y":1157,"z":-146},"victimPosition":{"x":1516,"y":871,"z":-152}},{"roundNumber":3,"tick":21285,"killerIndex":0,"victimIndex":8,"assisterIndex":3,"flashAssisterIndex":null,"weapon":"ak47","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":false,"flashAssist":false,"tradeKill":true,"tradeDeath":false,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":724,"y":1279,"z":-88},"victimPosition":{"x":878,"y":2133,"z":-40}},{"roundNumber":4,"tick":26766,"killerIndex":5,"victimIndex":1,"assisterIndex":null,"flashAssisterIndex":null,"weapon":"m4a1_silencer","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":true,"flashAssist":false,"tradeKill":false,"tradeDeath":true,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":582,"y":58,"z":-152},"victimPosition":{"x":1227,"y":736,"z":-152}},{"roundNumber":4,"tick":26825,"killerIndex":2,"victimIndex":5,"assisterIndex":null,"flashAssisterIndex":null,"weapon":"ak47","killerActiveWeapon":null,"victimActiveWeapon":null,"headshot":false,"flashAssist":false,"tradeKill":true,"tradeDeath":true,"throughSmoke":false,"noScope":false,"penetratedObjects":0,"killerPosition":{"x":1218,"y":600,"z":-152},"victimPosition":{"x":559,"y":76,"z":-1
