=== Starfie1d1272/cs2-demo-format/spec/playerEconomies.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "roundNumber": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "playerIndex": {
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      },
      "startMoney": {
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      },
      "moneySpent": {
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      },
      "equipmentValue": {
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      },
      "type": {
        "type": "string",
        "enum": [
          "pistol",
          "eco",
          "semi",
          "force",
          "full"
        ]
      },
      "hasArmor": {
        "type": "boolean"
      },
      "hasHelmet": {
        "type": "boolean"
      },
      "hasDefuseKit": {
        "type": "boolean"
      },
      "primaryWeapon": {
        "type": [
          "string",
          "null"
        ]
      },
      "secondaryWeapon": {
        "type": [
          "string",
          "null"
        ]
      },
      "grenadeCount": {
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      },
      "grenades": {
        "default": [],
        "type": "array",
        "items": {
          "type": "string",
          "enum": [
            "flashbang",
            "smoke",
            "molotov",
            "incendiary",
            "hegrenade",
            "decoy"
          ]
        }
      }
    },
    "required": [
      "roundNumber",
      "playerIndex",
      "startMoney",
      "moneySpent",
      "equipmentValue",
      "type",
      "hasArmor",
      "hasHelmet",
      "hasDefuseKit",
      "primaryWeapon",
      "secondaryWeapon",
      "grenadeCount"
    ],
    "additionalProperties": false
  }
}

=== Starfie1d1272/cs2-demo-format/fixtures/v3-mid/player-economies.json
[{"roundNumber":1,"playerIndex":6,"startMoney":800,"moneySpent":650,"equipmentValue":850,"type":"pistol","hasArmor":true,"hasHelmet":false,"hasDefuseKit":false,"primaryWeapon":null,"secondaryWeapon":"USP-S","grenadeCount":0},{"roundNumber":1,"playerIndex":2,"startMoney":800,"moneySpent":650,"equipmentValue":850,"type":"pistol","hasArmor":true,"hasHelmet":false,"hasDefuseKit":false,"primaryWeapon":null,"secondaryWeapon":"Glock-18","grenadeCount":0},{"roundNumber":1,"playerIndex":0,"startMoney":800,"moneySpent":650,"equipmentValue":950,"type":"pistol","hasArmor":true,"hasHelmet":false,"hasDefuseKit":false,"primaryWeapon":null,"secondaryWeapon":"P250","grenadeCount":0},{"roundNumber":1,"playerIndex":8,"startMoney":800,"moneySpent":650,"equipmentValue":850,"type":"pistol","hasArmor":true,"hasHelmet":false,"hasDefuseKit":false,"primaryWeapon":null,"secondaryWeapon":"USP-S","grenadeCount":0},{"roundNumber":1,"playerIndex":4,"startMoney":800,"moneySpent":800,"equipmentValue":700,"type":"pistol","hasArmor":false,"hasHelmet":false,"hasDefuseKit":false,"primaryWeapon":null,"secondaryWeapon":"Glock-18","grenadeCount":2},{"roundNumber":1,"playerIndex":3,"startMoney":800,"moneySpent":650,"equipmentValue":850,"type":"pistol","hasArmor":true,"hasHelmet":false,"hasDefuseKit":false,"primaryWeapon":null,"secondaryWeapon":"Glock-18","grenadeCount":0},{"roundNumber":1,"playerIndex":1,"startMoney":800,"moneySpent":650,"equipmentValue":850,"type":"pistol","hasArmor":true,"hasHelmet":false,"hasDefuseKit":false,"primaryWeapon":null,"secondaryWeapon":"Glock-18","grenadeCount":0},{"roundNumber":1,"playerIndex":9,"startMoney":800,"moneySpent":650,"equipmentValue":850,"type":"pistol","hasArmor":true,"hasHelmet":false,"hasDefuseKit":false,"primaryWeapon":null,"secondaryWeapon":"USP-S","grenadeCount":0},{"roundNumber":1,"playerIndex":7,"startMoney":800,"moneySpent":650,"equipmentValue":850,"type":"pistol","hasArmor":true,"hasHelmet":false,"hasDefuseKit":false,"primaryWeapon":null,"secondaryWeapon":"USP-S","grenadeCount":0},{"roundNumber":1,"playerIndex":5,"startMoney":800,"moneySpent":700,"equipmentValue":900,"type":"pistol","hasArmor":false,"hasHelmet":false,"hasDefuseKit":true,"primaryWeapon":null,"secondaryWeapon":"USP-S","grenadeCount":1},{"roundNumber":2,"playerIndex":6,"startMoney":2250,"moneySpent":0,"equipmentValue":200,"type":"eco","hasArmor":false,"hasHelmet":false,"hasDefuseKit":false,"primaryWeapon":null,"secondaryWeapon":"USP-S","grenadeCount":0},{"roundNumber":2,"playerIndex":2,"startMoney":4000,"moneySpent":4000,"equipmentValue":4200,"type":"full","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"AK-47","secondaryWeapon":"Glock-18","grenadeCount":1},{"roundNumber":2,"playerIndex":0,"startMoney":3700,"moneySpent":2750,"equipmentValue":2950,"type":"semi","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"MAC-10","secondaryWeapon":"Glock-18","grenadeCount":3},{"roundNumber":2,"playerIndex":8,"startMoney":2850,"moneySpent":700,"equipmentValue":700,"type":"eco","hasArmor":false,"hasHelmet":false,"hasDefuseKit":false,"primaryWeapon":null,"secondaryWeapon":"Desert Eagle","grenadeCount":0},{"roundNumber":2,"playerIndex":4,"startMoney":3250,"moneySpent":2750,"equipmentValue":2950,"type":"force","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"MAC-10","secondaryWeapon":"Glock-18","grenadeCount":3},{"roundNumber":2,"playerIndex":3,"startMoney":4300,"moneySpent":3700,"equipmentValue":3900,"type":"force","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"Galil AR","secondaryWeapon":"Glock-18","grenadeCount":3},{"roundNumber":2,"playerIndex":1,"startMoney":3400,"moneySpent":3300,"equipmentValue":3500,"type":"force","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"Galil AR","secondaryWeapon":"Glock-18","grenadeCount":2},{"roundNumber":2,"playerIndex":9,"startMoney":2250,"moneySpent":0,"equipmentValue":200,"type":"eco","hasArmor":false,"hasHelmet":false,"hasDefuseKit":false,"primaryWeapon":null,"secondaryWeapon":"USP-S","grenadeCount":0},{"roundNumber":2,"playerIndex":7,"startMoney":2250,"moneySpent":0,"equipmentValue":200,"type":"eco","hasArmor":false,"hasHelmet":false,"hasDefuseKit":false,"primaryWeapon":null,"secondaryWeapon":"USP-S","grenadeCount":0},{"roundNumber":2,"playerIndex":5,"startMoney":2800,"moneySpent":0,"equipmentValue":200,"type":"eco","hasArmor":false,"hasHelmet":false,"hasDefuseKit":false,"primaryWeapon":null,"secondaryWeapon":"USP-S","grenadeCount":0},{"roundNumber":3,"playerIndex":6,"startMoney":5000,"moneySpent":5000,"equipmentValue":5200,"type":"full","hasArmor":true,"hasHelmet":true,"hasDefuseKit":true,"primaryWeapon":"M4A1-S","secondaryWeapon":"USP-S","grenadeCount":2},{"roundNumber":3,"playerIndex":2,"startMoney":3550,"moneySpent":700,"equipmentValue":5100,"type":"full","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"AK-47","secondaryWeapon":"Glock-18","grenadeCount":4},{"roundNumber":3,"playerIndex":0,"startMoney":4200,"moneySpent":1700,"equipmentValue":4600,"type":"full","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"AK-47","secondaryWeapon":"Glock-18","grenadeCount":3},{"roundNumber":3,"playerIndex":8,"startMoney":4600,"moneySpent":4500,"equipmentValue":4700,"type":"full","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"M4A1-S","secondaryWeapon":"USP-S","grenadeCount":2},{"roundNumber":3,"playerIndex":4,"startMoney":4950,"moneySpent":900,"equipmentValue":3350,"type":"semi","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"MAC-10","secondaryWeapon":"Glock-18","grenadeCount":4},{"roundNumber":3,"playerIndex":3,"startMoney":4150,"moneySpent":3200,"equipmentValue":3900,"type":"semi","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"Galil AR","secondaryWeapon":"Glock-18","grenadeCount":3},{"roundNumber":3,"playerIndex":1,"startMoney":3950,"moneySpent":1000,"equipmentValue":4200,"type":"full","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"Galil AR","secondaryWeapon":"Glock-18","grenadeCount":4},{"roundNumber":3,"playerIndex":9,"startMoney":4700,"moneySpent":4600,"equipmentValue":4800,"type":"full","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"M4A1-S","secondaryWeapon":"USP-S","grenadeCount":3},{"roundNumber":3,"playerIndex":7,"startMoney":4700,"moneySpent":4700,"equipmentValue":4900,"type":"full","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"M4A1-S","secondaryWeapon":"USP-S","grenadeCount":2},{"roundNumber":3,"playerIndex":5,"startMoney":4950,"moneySpent":4900,"equipmentValue":5100,"type":"full","hasArmor":true,"hasHelmet":true,"hasDefuseKit":true,"primaryWeapon":"M4A1-S","secondaryWeapon":"USP-S","grenadeCount":2},{"roundNumber":4,"playerIndex":6,"startMoney":3050,"moneySpent":1300,"equipmentValue":3200,"type":"semi","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":null,"secondaryWeapon":"USP-S","grenadeCount":1},{"roundNumber":4,"playerIndex":2,"startMoney":6100,"moneySpent":4400,"equipmentValue":4600,"type":"full","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"AK-47","secondaryWeapon":"Glock-18","grenadeCount":2},{"roundNumber":4,"playerIndex":0,"startMoney":6050,"moneySpent":0,"equipmentValue":4900,"type":"full","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"AK-47","secondaryWeapon":"Glock-18","grenadeCount":3},{"roundNumber":4,"playerIndex":8,"startMoney":3450,"moneySpent":3450,"equipmentValue":3650,"type":"force","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"FAMAS","secondaryWeapon":"USP-S","grenadeCount":2},{"roundNumber":4,"playerIndex":4,"startMoney":7300,"moneySpent":2200,"equipmentValue":5300,"type":"full","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"M4A1-S","secondaryWeapon":"Glock-18","grenadeCount":4},{"roundNumber":4,"playerIndex":3,"startMoney":5100,"moneySpent":4600,"equipmentValue":4800,"type":"full","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"AK-47","secondaryWeapon":"Glock-18","grenadeCount":3},{"roundNumber":4,"playerIndex":1,"startMoney":6800,"moneySpent":3700,"equipmentValue":5100,"type":"full","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"AK-47","secondaryWeapon":"Glock-18","grenadeCount":4},{"roundNumber":4,"playerIndex":9,"startMoney":3150,"moneySpent":1450,"equipmentValue":1450,"type":"semi","hasArmor":true,"hasHelmet":false,"hasDefuseKit":false,"primaryWeapon":null,"secondaryWeapon":"Five-SeveN","grenadeCount":1},{"roundNumber":4,"playerIndex":7,"startMoney":3050,"moneySpent":2900,"equipmentValue":3100,"type":"force","hasArmor":true,"hasHelmet":false,"hasDefuseKit":false,"primaryWeapon":"FAMAS","secondaryWeapon":"USP-S","grenadeCount":1},{"roundNumber":4,"playerIndex":5,"startMoney":3700,"moneySpent":3550,"equipmentValue":3750,"type":"force","hasArmor":true,"hasHelmet":false,"hasDefuseKit":false,"primaryWeapon":"M4A1-S","secondaryWeapon":"USP-S","grenadeCount":0},{"roundNumber":5,"playerIndex":6,"startMoney":3750,"moneySpent":3750,"equipmentValue":3950,"type":"force","hasArmor":true,"hasHelmet":false,"hasDefuseKit":false,"primaryWeapon":"M4A1-S","secondaryWeapon":"USP-S","grenadeCount":1},{"roundNumber":5,"playerIndex":2,"startMoney":5250,"moneySpent":4900,"equipmentValue":5100,"type":"full","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"AK-47","secondaryWeapon":"Glock-18","grenadeCount":4},{"roundNumber":5,"playerIndex":0,"startMoney":10200,"moneySpent":3350,"equipmentValue":4900,"type":"full","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"AK-47","secondaryWeapon":"Glock-18","grenadeCount":4},{"roundNumber":5,"playerIndex":8,"startMoney":4200,"moneySpent":4200,"equipmentValue":4400,"type":"full","hasArmor":true,"hasHelmet":true,"hasDefuseKit":false,"primaryWeapon":"M4A1-S","secondaryWeapo
